name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: |
        sudo npm i -g babelify browserify mocha
        sudo apt install ruby
    - name: build, test
      run: |
        npm i
        npm run build
        npm run test
